import {
  RiBox3Line,
  RiBox3Fill,
  RiBarcodeBoxLine,
  RiBarcodeBoxFill,
  RiQrCodeLine,
  RiPhoneLine,
  RiMapPinLine,
  RiBuilding4Line,
  RiTruckLine,
  RiPlaneLine,
  RiPlaneFill,
  RiFileList3Line,
  RiFileList3Fill,
  RiDashboardLine,
  RiUserLine,
  RiCheckboxCircleLine,
  RiErrorWarningLine,
  RiLoader4Line,
  RiCloseCircleLine,
  RiArrowRightLine,
  RiArrowLeftLine,
  RiLogoutBoxRLine,
  RiLoginBoxLine,
  RiShieldCheckLine,
  RiTeamLine,
  RiRobot2Line,
  RiExchangeFundsLine,
  RiExchangeFundsFill,
  RiMoonClearLine,
  RiSunLine,
  RiMenuLine,
  RiGithubFill,
  RiFlightTakeoffLine,
  RiScanLine,
  RiScanFill,
  RiStore2Line,
  RiAlertLine,
  RiAlertFill,
  RiBarChart2Line,
  RiBarChart2Fill,
  RiSettingsLine,
  RiNotification3Line,
  RiSearchLine,
  RiCloseLine,
  RiHomeLine,
  RiHeadphoneLine,
  RiBuildingLine,
  RiAddLine,
  RiCheckLine,
  RiCheckFill,
  RiRefreshLine,
  RiWifiOffLine,
  RiWifiLine,
  RiExternalLinkLine,
  RiArrowUpLine,
  RiArrowDownLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiDownloadLine,
  RiUploadLine,
  RiEyeLine,
  RiEditLine,
  RiDeleteBinLine,
  RiMoreLine,
  RiLoaderLine,
  RiFilterLine,
  RiArrowDownSLine,
  RiCalendarLine,
  RiPrinterLine,
  RiFileTextLine,
  RiFileCopyLine,
  RiInformationLine,
  RiTimeLine,
  RiTimeFill,
  RiMapLine,
  RiFlashlightLine,
  RiMailLine,
  RiMoneyDollarCircleLine,
  RiUserAddLine,
  RiUserForbidLine,
  RiPassportLine,
  RiListCheck3,
  RiCalculatorLine,
  RiPlugLine,
  RiCpuLine,
  RiTerminalBoxLine,
  RiRocketLine,
  RiAccountCircleLine,
  RiHistoryLine,
  RiKey2Line,
  RiSendPlaneLine,
  RiWhatsappLine,
  RiHome2Line,
  RiShipLine,
  RiLeafLine,
  RiSubtractLine,
  RiCircleFill,
  RiMore2Line,
  RiBold as RiBoldLine,
  RiItalic as RiItalicLine,
  RiUnderline,
  RiStrikethrough,
  RiH1,
  RiH2,
  RiH3,
  RiListUnordered,
  RiListOrdered,
  RiDoubleQuotesL,
  RiCodeLine,
  RiLinkM,
  RiImageLine,
  RiAlignLeft,
  RiAlignCenter,
  RiAlignRight,
  RiAlignJustify,
  RiSeparator,
  RiArrowGoBackLine,
  RiArrowGoForwardLine,
  RiCameraLine,
  RiVolumeMuteLine,
  RiVolumeUpLine,
  RiZoomInLine,
  RiZoomOutLine,
  RiContrastLine,
  RiBugLine,
  RiCloudOffLine,
  RiKeyLine,
  RiBookOpenLine,
  RiPaletteLine,
  RiNotionLine,
  RiSignalTowerLine,
  RiBubbleChartLine,
  RiCommandLine,
  RiKeyboardLine,
  RiPushpinLine,
  RiBookmarkLine,
  RiSparkling2Line,
  RiBrushLine,
  RiTaskLine,
  RiArchiveLine,
  RiSignalWifiErrorLine,
  RiInboxLine,
  RiArrowRightUpLine,
  RiClipboardLine,
  RiGridLine,
  RiYoutubeFill,
} from "@remixicon/react"
export type { RemixiconComponentType } from "@remixicon/react"

export {
  RiSubtractLine,
  RiCircleFill,
  RiMore2Line,
  RiBoldLine,
  RiItalicLine,
  RiUnderline,
  RiStrikethrough,
  RiH1,
  RiH2,
  RiH3,
  RiListUnordered,
  RiListOrdered,
  RiDoubleQuotesL,
  RiCodeLine,
  RiLinkM,
  RiImageLine,
  RiAlignLeft,
  RiAlignCenter,
  RiAlignRight,
  RiAlignJustify,
  RiSeparator,
  RiArrowGoBackLine,
  RiArrowGoForwardLine,
  RiCameraLine,
  RiVolumeMuteLine,
  RiVolumeUpLine,
  RiZoomInLine,
  RiZoomOutLine,
  RiContrastLine,
  RiBugLine,
  RiRefreshLine as RiSyncLine,
  RiCloudOffLine,
  RiKeyLine,
  RiBookOpenLine,
  RiPaletteLine,
  RiNotionLine,
  RiSignalTowerLine,
  RiBubbleChartLine,
  RiCommandLine,
  RiKeyboardLine,
  RiPushpinLine,
  RiBookmarkLine,
  RiSparkling2Line,
  RiBrushLine,
  RiTaskLine,
  RiArchiveLine,
  RiSignalWifiErrorLine,
}

// Create a mapping of keys to Remix Icons, enforcing standard naming
export const LogisticsIcons = {
  package: RiBox3Line,
  barcode: RiBarcodeBoxLine,
  qr: RiQrCodeLine,
  phone: RiPhoneLine,
  location: RiMapPinLine,
  hub: RiBuilding4Line,
  truck: RiTruckLine,
  plane: RiPlaneLine,
  invoice: RiFileList3Line,
  dashboard: RiDashboardLine,
  user: RiUserLine,
  checkCircle: RiCheckboxCircleLine,
  warning: RiErrorWarningLine,
  error: RiCloseCircleLine,
  arrowRight: RiArrowRightLine,
  arrowLeft: RiArrowLeftLine,
  logout: RiLogoutBoxRLine,
  login: RiLoginBoxLine,
  shield: RiShieldCheckLine,
  team: RiTeamLine,
  robot: RiRobot2Line,
  exchange: RiExchangeFundsLine,
  moon: RiMoonClearLine,
  sun: RiSunLine,
  menu: RiMenuLine,
  github: RiGithubFill,
  flightTakeoff: RiFlightTakeoffLine,
  add: RiAddLine,
  check: RiCheckLine,
  refresh: RiRefreshLine,
  wifiOff: RiWifiOffLine,
  scan: RiScanLine,
  warehouse: RiStore2Line,
  alert: RiAlertLine,
  barChart: RiBarChart2Line,
  settings: RiSettingsLine,
  notification: RiNotification3Line,
  search: RiSearchLine,
  close: RiCloseLine,
  home: RiHomeLine,
  customer: RiHeadphoneLine,
  building: RiBuildingLine,
  sortAsc: RiArrowUpLine,
  sortDesc: RiArrowDownLine,
  chevronLeft: RiArrowLeftSLine,
  chevronRight: RiArrowRightSLine,
  chevronDown: RiArrowDownSLine,
  download: RiDownloadLine,
  upload: RiUploadLine,
  eye: RiEyeLine,
  edit: RiEditLine,
  trash: RiDeleteBinLine,
  more: RiMoreLine,
  loader: RiLoaderLine,
  filter: RiFilterLine,
  calendar: RiCalendarLine,
  printer: RiPrinterLine,
  fileText: RiFileTextLine,
  copy: RiFileCopyLine,
  info: RiInformationLine,
  clock: RiTimeLine,
  map: RiMapLine,
  flash: RiFlashlightLine,
  mail: RiMailLine,
  money: RiMoneyDollarCircleLine,
  userAdd: RiUserAddLine,
  userForbid: RiUserForbidLine,
  passport: RiPassportLine,
  listCheck: RiListCheck3,
  plug: RiPlugLine,
  cpu: RiCpuLine,
  terminal: RiTerminalBoxLine,
  rocket: RiRocketLine,
  userLine: RiAccountCircleLine,
  calculator: RiCalculatorLine,
  youtube: RiYoutubeFill,
}

export type IconName = keyof typeof LogisticsIcons

interface IconProps extends React.ComponentProps<typeof RiBox3Line> {
  name: IconName
}

export function Icon({ name, className, ...props }: IconProps) {
  const IconComponent = LogisticsIcons[name]

  if (!IconComponent) {
    console.warn(`Icon '${name}' not found in LogisticsIcons mapping.`)
    return null
  }

  return <IconComponent className={className} {...props} />
}

export {
  RiBox3Line,
  RiBox3Fill,
  RiBarcodeBoxLine,
  RiBarcodeBoxFill,
  RiQrCodeLine,
  RiPhoneLine,
  RiMapPinLine,
  RiBuilding4Line,
  RiTruckLine,
  RiPlaneLine,
  RiPlaneFill,
  RiFileList3Line,
  RiFileList3Fill,
  RiDashboardLine,
  RiUserLine,
  RiCheckboxCircleLine,
  RiErrorWarningLine,
  RiLoader4Line,
  RiCloseCircleLine,
  RiArrowRightLine,
  RiArrowLeftLine,
  RiLogoutBoxRLine,
  RiLoginBoxLine,
  RiShieldCheckLine,
  RiTeamLine,
  RiRobot2Line,
  RiExchangeFundsLine,
  RiExchangeFundsFill,
  RiMoonClearLine,
  RiSunLine,
  RiMenuLine,
  RiGithubFill,
  RiFlightTakeoffLine,
  RiScanLine,
  RiScanFill,
  RiAlertLine,
  RiAlertFill,
  RiBarChart2Line,
  RiBarChart2Fill,
  RiSettingsLine,
  RiNotification3Line,
  RiSearchLine,
  RiCloseLine,
  RiHomeLine,
  RiHeadphoneLine,
  RiStore2Line,
  RiBuildingLine,
  RiAddLine,
  RiCheckLine,
  RiCheckFill,
  RiRefreshLine,
  RiWifiOffLine,
  RiWifiLine,
  RiExternalLinkLine,
  RiArrowUpLine,
  RiArrowDownLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiDownloadLine,
  RiUploadLine,
  RiEyeLine,
  RiEditLine,
  RiDeleteBinLine,
  RiMoreLine,
  RiLoaderLine,
  RiFilterLine,
  RiArrowDownSLine,
  RiCalendarLine,
  RiPrinterLine,
  RiFileTextLine,
  RiFileCopyLine,
  RiInformationLine,
  RiTimeLine,
  RiTimeFill,
  RiMapLine,
  RiFlashlightLine,
  RiMailLine,
  RiMoneyDollarCircleLine,
  RiUserAddLine,
  RiUserForbidLine,
  RiPassportLine,
  RiListCheck3,
  RiCalculatorLine,
  RiPlugLine,
  RiCpuLine,
  RiTerminalBoxLine,
  RiRocketLine,
  RiAccountCircleLine,
  RiHistoryLine,
  RiKey2Line,
  RiSendPlaneLine,
  RiWhatsappLine,
  RiHome2Line,
  RiShipLine,
  RiLeafLine,
  RiInboxLine,
  RiArrowRightUpLine,
  RiClipboardLine,
  RiGridLine,
}
