-- Production schema snapshot — functions only
-- Source: Supabase project <YOUR_SUPABASE_PROJECT_ID>
-- Captured: 2026-05-14
-- Method: SELECT pg_get_functiondef(p.oid) FROM pg_proc via MCP
--
-- This file is the FROZEN REFERENCE for what production actually has, as of
-- the audit date. The repo's supabase/migrations/* files do NOT match this.
-- See REPO-VS-PRODUCTION-DIVERGENCE-2026-05-14.md for the full delta.
--
-- DO NOT EDIT this file. If production changes, regenerate via:
--   mcp__supabase__execute_sql with `SELECT pg_get_functiondef(...)` per function
-- and overwrite. The whole point of a snapshot is that it doesn't drift.

-- ============================================================================
-- TRIGGER / UTILITY FUNCTIONS
-- ============================================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.profiles (id, email, name)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1))
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.shipment_emit_created_event()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not exists (
    select 1 from public.tracking_events
    where awb_number = new.awb_number and status = 'CREATED'
  ) then
    insert into public.tracking_events
      (awb_number, status, description, location, hub_code, source, staff_id, created_at)
    values (
      new.awb_number,
      'CREATED',
      'Shipment created',
      coalesce(new.origin_hub, 'UNKNOWN'),
      coalesce(new.origin_hub, 'UNKNOWN'),
      'SYSTEM',
      new.created_by,
      coalesce(new.created_at, now())
    );
  end if;
  return new;
end;
$function$;

-- ============================================================================
-- NUMBER GENERATORS
-- ============================================================================

CREATE OR REPLACE FUNCTION public.generate_awb_number()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN 'TAC' || TO_CHAR(NOW() AT TIME ZONE 'UTC', 'YYMMDD') || LPAD(NEXTVAL('public.awb_seq')::text, 5, '0');
END;
$function$;

CREATE OR REPLACE FUNCTION public.generate_invoice_number()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN 'INV-' || TO_CHAR(NOW() AT TIME ZONE 'UTC', 'YYYY') || '-' || LPAD(NEXTVAL('public.invoice_seq')::text, 5, '0');
END;
$function$;

CREATE OR REPLACE FUNCTION public.generate_manifest_number()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN 'MAN' || TO_CHAR(NOW() AT TIME ZONE 'UTC', 'YYMMDD') || LPAD(NEXTVAL('public.manifest_seq')::text, 4, '0');
END;
$function$;

-- ============================================================================
-- AUTH / RBAC HELPERS
-- ============================================================================

CREATE OR REPLACE FUNCTION public.get_user_role()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT role FROM public.profiles WHERE id = auth.uid()
$function$;

-- ============================================================================
-- DOMAIN RPCs — mutating
-- ============================================================================

-- NOTE the RETURNS void — production returns nothing. Repo's #85 wrongly
-- declares RETURNS json. PostgreSQL won't allow CREATE OR REPLACE to change
-- return type; deploy would fail at the planning phase.

CREATE OR REPLACE FUNCTION public.add_shipment_to_manifest(p_manifest_id uuid, p_awb_number text, p_staff_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_shipment_id uuid;
  v_pieces      int;
  v_weight      numeric;
BEGIN
  SELECT id, pieces, chargeable_weight
  INTO v_shipment_id, v_pieces, v_weight
  FROM public.shipments
  WHERE awb_number = p_awb_number;

  IF v_shipment_id IS NULL THEN
    RAISE EXCEPTION 'Shipment not found: %', p_awb_number;
  END IF;

  INSERT INTO public.manifest_shipments (manifest_id, awb_number, shipment_id, added_by)
  VALUES (p_manifest_id, p_awb_number, v_shipment_id, p_staff_id);

  UPDATE public.shipments
  SET manifest_id = p_manifest_id,
      manifest_number = (SELECT manifest_number FROM public.manifests WHERE id = p_manifest_id)
  WHERE id = v_shipment_id;

  UPDATE public.manifests
  SET
    total_shipments = total_shipments + 1,
    total_pieces    = total_pieces + COALESCE(v_pieces, 1),
    total_weight    = total_weight + COALESCE(v_weight, 0),
    updated_at      = now()
  WHERE id = p_manifest_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.close_manifest_atomic(p_manifest_id uuid, p_staff_id uuid DEFAULT NULL::uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_staff_id uuid := COALESCE(p_staff_id, auth.uid());
  v_count    integer;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM public.manifest_shipments
  WHERE manifest_id = p_manifest_id;

  UPDATE public.manifests
  SET
    status     = 'CLOSED',
    closed_by  = v_staff_id,
    updated_at = now()
  WHERE id = p_manifest_id AND status IN ('DRAFT','BUILDING','OPEN');

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Manifest % not found or cannot be closed from current status', p_manifest_id;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.depart_manifest(p_manifest_id uuid, p_staff_id uuid DEFAULT NULL::uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_staff_id uuid := COALESCE(p_staff_id, auth.uid());
BEGIN
  UPDATE public.manifests
  SET
    status      = 'DEPARTED',
    departed_by = v_staff_id,
    departed_at = now(),
    updated_at  = now()
  WHERE id = p_manifest_id AND status = 'CLOSED';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Manifest % not found or not in CLOSED status', p_manifest_id;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.arrive_manifest(p_manifest_id uuid, p_staff_id uuid DEFAULT NULL::uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_staff_id uuid := COALESCE(p_staff_id, auth.uid());
BEGIN
  UPDATE public.manifests
  SET
    status      = 'ARRIVED',
    arrived_by  = v_staff_id,
    arrived_at  = now(),
    updated_at  = now()
  WHERE id = p_manifest_id AND status = 'DEPARTED';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Manifest % not found or not in DEPARTED status', p_manifest_id;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.resolve_exception(p_exception_id uuid, p_staff_id uuid, p_resolution text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  UPDATE public.exceptions
  SET
    status      = 'RESOLVED',
    resolved_by = p_staff_id,
    resolution  = p_resolution,
    resolved_at = now(),
    updated_at  = now()
  WHERE id = p_exception_id AND status IN ('OPEN', 'IN_PROGRESS');

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Exception % not found or already resolved', p_exception_id;
  END IF;

  INSERT INTO public.audit_logs (entity_type, entity_id, action, description, user_id)
  VALUES ('exception', p_exception_id, 'RESOLVED', 'Exception resolved: ' || p_resolution, p_staff_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_shipment_status(p_shipment_id uuid, p_new_status text, p_staff_id uuid, p_notes text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_awb        text;
  v_staff_name text;
BEGIN
  SELECT awb_number INTO v_awb FROM public.shipments WHERE id = p_shipment_id;
  IF v_awb IS NULL THEN
    RAISE EXCEPTION 'Shipment not found: %', p_shipment_id;
  END IF;

  SELECT name INTO v_staff_name FROM public.profiles WHERE id = p_staff_id;

  UPDATE public.shipments
  SET
    status       = p_new_status,
    delivered_at = CASE WHEN p_new_status = 'DELIVERED' THEN now() ELSE delivered_at END,
    cancelled_at = CASE WHEN p_new_status = 'CANCELLED' THEN now() ELSE cancelled_at END,
    updated_at   = now()
  WHERE id = p_shipment_id;

  INSERT INTO public.tracking_events (awb_number, status, description, source, staff_id, staff_name)
  VALUES (
    v_awb,
    p_new_status,
    COALESCE(p_notes, 'Status updated to ' || p_new_status),
    'MANUAL',
    p_staff_id,
    v_staff_name
  );

  INSERT INTO public.audit_logs (entity_type, entity_id, action, description, user_id)
  VALUES ('shipment', p_shipment_id, 'STATUS_CHANGE', 'Status changed to ' || p_new_status, p_staff_id);
END;
$function$;

-- ============================================================================
-- DOMAIN RPCs — read-only / aggregate
-- ============================================================================

CREATE OR REPLACE FUNCTION public.count_shipments_by_status()
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  result json;
BEGIN
  SELECT json_object_agg(status, cnt)
  INTO result
  FROM (
    SELECT status, COUNT(*)::int AS cnt
    FROM public.shipments
    GROUP BY status
  ) t;
  RETURN COALESCE(result, '{}'::json);
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_finance_summary()
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_total_revenue  numeric;
  v_outstanding    numeric;
  v_paid_count     int;
BEGIN
  SELECT
    COALESCE(SUM(CASE WHEN status = 'PAID' THEN total_amount ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN status IN ('ISSUED', 'OVERDUE') THEN balance ELSE 0 END), 0),
    COUNT(CASE WHEN status = 'PAID' THEN 1 END)::int
  INTO v_total_revenue, v_outstanding, v_paid_count
  FROM public.invoices;

  RETURN json_build_object(
    'totalRevenue',  v_total_revenue,
    'outstanding',   v_outstanding,
    'paidCount',     v_paid_count
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_rate_card(p_origin text, p_dest text, p_service_level text, p_weight numeric)
 RETURNS TABLE(id uuid, rate_per_kg numeric, docket_charge numeric, fuel_surcharge_pct numeric, handling_fee numeric)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT
    rc.id,
    rc.rate_per_kg,
    rc.docket_charge,
    rc.fuel_surcharge_pct,
    rc.handling_fee
  FROM public.rate_cards rc
  WHERE rc.origin_hub = p_origin
    AND rc.dest_hub = p_dest
    AND rc.service_level = p_service_level
    AND rc.weight_slab_min <= p_weight
    AND rc.weight_slab_max >= p_weight
    AND rc.is_active = true
  ORDER BY rc.weight_slab_min DESC
  LIMIT 1;
$function$;

CREATE OR REPLACE FUNCTION public.generate_invoice(p_shipment_id uuid, p_staff_id uuid, p_discount numeric DEFAULT 0)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_shipment     record;
  v_invoice_id   uuid;
  v_base_freight numeric;
  v_total        numeric;
BEGIN
  SELECT * INTO v_shipment FROM public.shipments WHERE id = p_shipment_id;
  IF v_shipment IS NULL THEN
    RAISE EXCEPTION 'Shipment not found: %', p_shipment_id;
  END IF;

  v_base_freight := v_shipment.chargeable_weight * v_shipment.rate_per_kg;
  v_total        := GREATEST(0, v_base_freight - p_discount);

  INSERT INTO public.invoices (
    awb_number, shipment_id, customer_id, customer_name,
    payment_mode, base_freight, discount, total_amount, balance,
    status, created_by
  )
  VALUES (
    v_shipment.awb_number,
    p_shipment_id,
    v_shipment.customer_id,
    COALESCE((SELECT name FROM public.customers WHERE id = v_shipment.customer_id), v_shipment.sender_name),
    v_shipment.payment_mode,
    v_base_freight,
    p_discount,
    v_total,
    v_total,
    'DRAFT',
    p_staff_id
  )
  RETURNING id INTO v_invoice_id;

  RETURN v_invoice_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.record_invoice_payment(
  p_invoice_id      uuid,
  p_amount          numeric,
  p_method          text,
  p_reference       text DEFAULT NULL::text,
  p_notes           text DEFAULT NULL::text,
  p_received_at     timestamp with time zone DEFAULT now(),
  p_attachment_path text DEFAULT NULL::text
)
 RETURNS invoice_payments
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_invoice     public.invoices%rowtype;
  v_new_balance numeric(12,2);
  v_new_advance numeric(12,2);
  v_payment     public.invoice_payments%rowtype;
begin
  if not exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('SUPER_ADMIN','OPERATOR')) then
    raise exception 'Unauthorized: only operators or super admins can record payments.' using errcode = '42501';
  end if;
  if p_amount <= 0 then
    raise exception 'Payment amount must be positive (got %).', p_amount using errcode = '22023';
  end if;
  select * into v_invoice from public.invoices where id = p_invoice_id for update;
  if not found then
    raise exception 'Invoice % not found.', p_invoice_id using errcode = 'P0002';
  end if;
  if v_invoice.status in ('CANCELLED','PAID') then
    raise exception 'Cannot record payment on a % invoice.', v_invoice.status using errcode = '22023';
  end if;
  insert into public.invoice_payments
    (invoice_id, amount, method, reference, notes, received_at, attachment_path, created_by)
  values
    (p_invoice_id, p_amount, p_method, p_reference, p_notes, p_received_at, p_attachment_path, auth.uid())
  returning * into v_payment;
  v_new_advance := coalesce(v_invoice.advance_paid, 0) + p_amount;
  v_new_balance := greatest(0, v_invoice.total_amount - v_new_advance);
  update public.invoices
  set advance_paid = v_new_advance,
      balance      = v_new_balance,
      status       = case when v_new_balance = 0 then 'PAID' else 'ISSUED' end,
      paid_at      = case when v_new_balance = 0 then coalesce(paid_at, now()) else paid_at end,
      updated_at   = now()
  where id = p_invoice_id;
  return v_payment;
end;
$function$;

-- ============================================================================
-- NOTE: production has NO `lookup_rate` function (repo defines one).
-- Production uses `get_rate_card` (different signature, different return type).
-- The app code calls one or the other depending on the repo's database.types.ts
-- — current types match `get_rate_card`.
-- ============================================================================

-- IMPORTANT — production has NO role gates on the 6 mutating RPCs above.
-- record_invoice_payment is the ONLY RPC with an embedded role check:
--   role IN ('SUPER_ADMIN', 'OPERATOR')
-- production.profiles.role CHECK constraint allows:
--   SUPER_ADMIN, ADMIN, MANAGER, WAREHOUSE_IMPHAL, WAREHOUSE_DELHI,
--   OPS, INVOICE, SUPPORT, WAREHOUSE_STAFF, OPS_STAFF, FINANCE_STAFF
-- → SUPER_ADMIN is present, so SUPER_ADMIN callers pass the gate
-- → OPERATOR is NOT present, so that branch never matches any row
-- → Net effect: record_invoice_payment in production rejects every
--   non-SUPER_ADMIN caller. Operational roles (OPS, OPS_STAFF, INVOICE,
--   FINANCE_STAFF) all get 42501 Unauthorized — even though they're
--   exactly the roles operationally responsible for recording payments.
--   The 6 existing invoice_payments rows were either inserted directly
--   (bypassing the RPC) or by a SUPER_ADMIN account. Worth confirming
--   via prod logs once Sentry is wired (#22).
